version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Amsterdam"
    commit-message:
      prefix: "build"
    labels:
      - "area: build & ci"
      - "target: patch"
      - "action: merge"
    open-pull-requests-limit: 5
