user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    server {
            listen       80;
            listen  [::]:80;
            server_name  nails.com;

            #location / {
            #    root   /usr/share/nginx/html;
            #    index  index.html index.htm;
            #    try_files $uri $uri/ /index.html;
            # }

            location / {
                    rewrite ^ https://$host$request_uri?$args permanent;
            }
    }

   server {
           listen 443 ssl http2;
           listen [::]:443 ssl http2;
           server_name nails.com;

           server_tokens off;

           ssl_certificate /etc/nginx/certs/server.crt;
           ssl_certificate_key /etc/nginx/certs/server.key;

           ssl_buffer_size 8k;

           ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
           ssl_prefer_server_ciphers on;

           ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

           ssl_ecdh_curve secp384r1;
           ssl_session_tickets off;

           resolver 8.8.8.8;

           gzip on;
           gzip_types text/css application/javascript;

           root   /usr/share/nginx/html;
           index index.html;

           location ~* (service-worker\.js)$ {
             # tells browsers the service worker scope
             add_header 'Service-Worker-Allowed' '/';
           }

           location /index.html {
               try_files $uri /index.html;

               add_header Cache-Control "no-store, no-cache, must-revalidate";
           }

           location / {
               try_files $uri /index.html;

               expires 1y;
               add_header Cache-Control "public";
           }
   }
}
