import {
  approveReservation,
  cancelReservation,
  clean,
  colorsCompleteSuccess,
  completeReservation,
  createReservation,
  createReview,
  customerCancelReservation,
  customerSearchReservation,
  customersSuccess,
  customerSuccess,
  deleteReservation,
  executeTrackingByReservationId,
  findRooms,
  getAllAdditionalByGroupId,
  getAllFilterReservations,
  getAllGroupingByRoom,
  getAllRooms,
  getAllTreatments,
  getColorsByTreatmentId,
  getCustomerInformation,
  getCustomerReservations,
  getCustomers,
  getEditReservation,
  getPage,
  getReservation,
  getReservationHistory,
  getReview,
  getTrackingByReservationId,
  getUpcomingReservation,
  paymentCompleteReservation,
  paymentOptions,
  paymentOptionsSuccess,
  reservationAdditionalSuccess,
  reservationFailure,
  reservationFilterPageSuccess,
  reservationFindPayments,
  reservationHistorySuccess,
  reservationPageSuccess,
  reservationPaymentsSuccess,
  reservationReviewSuccess,
  reservationRoomsSuccess,
  reservationSaveSuccess,
  reservationsCustomerSuccess,
  reservationSelected,
  reservationSuccess,
  reservationTreatmentsSuccess,
  searchAvailability,
  startReservation,
  stateSuccess,
  trackingSuccess,
  updateReservationById,
  updateReservationDiscount,
  updateReservationNote,
  updateReservationTimestamp,
  updateTrackingByReservationId,
} from '../reservation.actions';
import {
  IAvailableDTO,
  ICustomerLastReservation,
  ICustomerReservation,
  IReservation,
  IRoomReservation,
  ITracking,
} from '../../interfaces/reservation';
import { IUser } from '../../interfaces/user';
import { ITreatmentDiscountDTO } from '../../interfaces/treatment';
import { IRoom } from '../../interfaces/room';
import { Pagination } from '../../interfaces/pagination';
import { IPayment, IPaymentOption } from '../../interfaces/payment';
import { IAdditional } from '../../interfaces/additional';
import { IOffice } from '../../interfaces/office';
import { IColor } from '../../interfaces/color';
import { IReview } from '../../interfaces/review';
import { IError, IResponseSuccess } from '../../interfaces/common';
import { createReducer, on } from '@ngrx/store';

export interface State {
  response?: IResponseSuccess;
  data?: IReservation | IRoomReservation[] | IReservation[] | ICustomerReservation | IAvailableDTO;
  filter?: Pagination<IReservation>;
  page?: Pagination<IReservation>;
  customerReservation?: ICustomerReservation;
  customers?: IUser[];
  offices?: IOffice[];
  customer?: ICustomerLastReservation;
  rooms?: IRoom[];
  additional?: IAdditional[];
  treatmentDiscount?: ITreatmentDiscountDTO[];
  tracking?: ITracking[] | ITracking;
  payments?: IPayment[];
  history?: IReservation[];
  colors?: IColor[];
  paymentOptions?: IPaymentOption[];
  review?: IReview;
  errorMessage?: string;
  error?: IError;
  subErrors?: IError[];
  selected?: IReservation;
  isLoading: boolean;
}

export const initialState: State = {
  data: undefined,
  filter: undefined,
  page: undefined,
  customerReservation: undefined,
  customers: undefined,
  offices: undefined,
  customer: undefined,
  rooms: undefined,
  additional: undefined,
  treatmentDiscount: undefined,
  tracking: undefined,
  payments: undefined,
  history: undefined,
  colors: undefined,
  paymentOptions: undefined,
  review: undefined,
  errorMessage: undefined,
  error: undefined,
  subErrors: undefined,
  selected: undefined,
  response: undefined,
  isLoading: false,
};

export const reservationReducer = createReducer(
  initialState,
  on(getCustomerReservations, (state) => ({
    ...state,
    customerReservation: {
      reservations: { content: [{}, {}, {}], totalElements: 3 },
      upcoming: [{}],
    } as ICustomerReservation,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getAllFilterReservations, (state) => ({
    ...state,
    filter: { content: [{}, {}, {}], totalElements: 3 } as Pagination<IReservation>,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getPage, (state) => ({
    ...state,
    page: { content: [{}, {}, {}], totalElements: 3 } as Pagination<IReservation>,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getAllGroupingByRoom, (state) => ({
    ...state,
    data: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
    isLoading: true,
  })),
  on(getUpcomingReservation, (state) => ({
    ...state,
    data: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(customerSearchReservation, searchAvailability, (state) => ({
    ...state,
    data: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
    isLoading: true,
  })),
  on(getCustomers, (state) => ({
    ...state,
    customers: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getCustomerInformation, (state) => ({
    ...state,
    customer: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getAllRooms, findRooms, (state) => ({
    ...state,
    rooms: undefined,
    isLoading: true,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(getAllAdditionalByGroupId, (state) => ({
    ...state,
    additional: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(getAllTreatments, (state) => ({
    ...state,
    treatmentDiscount: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(updateReservationNote, updateReservationDiscount, updateReservationTimestamp, updateReservationById, (state) => ({
    ...state,
    data: {} as IReservation,
    page: undefined,
    filter: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
    isLoading: true,
  })),
  on(reservationFindPayments, (state) => ({
    ...state,
    payments: [{}, {}, {}],
    page: undefined,
    filter: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(getReservationHistory, (state) => ({
    ...state,
    history: [{}, {}, {}],
    page: undefined,
    filter: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(approveReservation,
    startReservation,
    completeReservation,
    paymentCompleteReservation,
    cancelReservation,
    customerCancelReservation,
    getEditReservation,
    getReservation, (state) => ({
      ...state,
      data: {} as IReservation,
      page: undefined,
      filter: undefined,
      errorMessage: undefined,
      error: undefined,
      subErrors: undefined,
      selected: undefined,
      response: undefined,
    })),
  on(reservationPageSuccess, (state, { page }) => ({
    ...state,
    page,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationFilterPageSuccess, (state, { filter }) => ({
    ...state,
    filter,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationsCustomerSuccess, (state, { customerReservation }) => ({
    ...state,
    customerReservation,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationSuccess, (state, { data }) => ({
    ...state,
    data,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(customersSuccess, (state, { customers }) => ({
    ...state,
    customers,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(customerSuccess, (state, { customer }) => ({
    ...state,
    customer,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationRoomsSuccess, (state, { rooms }) => ({
    ...state,
    rooms,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(reservationTreatmentsSuccess, (state, { treatmentDiscount }) => ({
    ...state,
    treatmentDiscount,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationAdditionalSuccess, (state, { additional }) => ({
    ...state,
    additional,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(stateSuccess, reservationSaveSuccess, (state, action) => ({
    ...state,
    response: action,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    isLoading: false,
  })),
  on(reservationSelected, (state, { selected }) => ({
    ...state,
    selected: selected,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(reservationFailure, (state, { error }) => ({
    ...state,
    errorMessage: error.message,
    error: error,
    subErrors: error.subErrors,
    response: undefined,
    isLoading: false,
  })),
  on(createReservation, deleteReservation, (state) => ({
    ...state,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: true,
  })),
  on(updateTrackingByReservationId, executeTrackingByReservationId, (state) => ({
    ...state,
    tracking: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(getTrackingByReservationId, (state) => ({
    ...state,
    tracking: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    selected: undefined,
    response: undefined,
  })),
  on(trackingSuccess, (state, { tracking }) => ({
    ...state,
    tracking,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationPaymentsSuccess, (state, { payments }) => ({
    ...state,
    payments,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(reservationHistorySuccess, (state, { history }) => ({
    ...state,
    history,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(createReview, (state) => ({
    ...state,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(getReview, (state) => ({
    ...state,
    review: undefined,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(reservationReviewSuccess, (state, { review }) => ({
    ...state,
    review,
    errorMessage: undefined,
    error: undefined,
    subErrors: undefined,
    response: undefined,
    isLoading: false,
  })),
  on(getColorsByTreatmentId, (state) => ({
    ...state,
    colors: undefined,
    errorMessage: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(colorsCompleteSuccess, (state, { colors }) => ({
    ...state,
    colors,
    errorMessage: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(paymentOptions, (state) => ({
    ...state,
    paymentOptions: undefined,
    errorMessage: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(paymentOptionsSuccess, (state, { paymentOptions }) => ({
    ...state,
    paymentOptions,
    errorMessage: undefined,
    subErrors: undefined,
    response: undefined,
  })),
  on(clean, () => initialState),
);
