name: Create Pull Request for New Branches

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!develop'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Issue Number
        id: extract_issue
        run: |
          ISSUE_NUMBER=$(echo "${GITHUB_REF#refs/heads/}" | grep -oE '[0-9]+')
          echo "Extracted ISSUE_NUMBER: $ISSUE_NUMBER"
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Get Issue Title and Label
        id: get_issue_title_label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = parseInt(process.env.ISSUE_NUMBER);
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });
            const issueTitle = `#${issue_number} ${issue.title}`;
            const matches = issueTitle.match(/\[(.*?)\]/);
            const issueLabel = matches ? `${matches[1].toLowerCase()},FrontEnd` : 'FrontEnd';
            core.setOutput('issueTitle', issueTitle);
            core.setOutput('issueLabel', issueLabel);

      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: "develop"
          pr_title: ${{ steps.get_issue_title_label.outputs.issueTitle }}
          pr_body: |
            ## Check list

            - [x] Pull request pointing to `develop`
            - [x] Link Pull request to issue
            - [ ] Pull request is green

            Closes: #${{ env.ISSUE_NUMBER }}
          pr_assignee: "lucasscarlatta"
          pr_label: ${{ steps.get_issue_title_label.outputs.issueLabel }}
          pr_draft: false
          pr_allow_empty: true
          github_token: ${{ secrets.ADMIN_TOKEN }}
