name: Deploy

on:
  push:
    tags: [ v*.*.* ]

env:
  IMAGE_NAME: nails-cleos

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./scripts/amplify-deploy.sh ${{env.IMAGE_NAME}} main
