name: Develop

on:
  push:
    branches:
      - develop
    tags-ignore:
      - "**"

jobs:
  snapshot:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update rc version
        run: |
          git config --global user.email "espaciocleos@gmail.com"
          git config --global user.name "Espacio Cleos"
          git fetch
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/version-update.sh"

          # run script
          "${GITHUB_WORKSPACE}/version-update.sh" true
          git commit -am "Update rc version"
          git push
