name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  version:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release version
        id: version
        run: |
          git config --global user.email "espaciocleos@gmail.com"
          git config --global user.name "Espacio Cleos"
          git fetch
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/version-update.sh"

          # run script
          VERSION=$("${GITHUB_WORKSPACE}/version-update.sh")
          git commit -am "Update release version $VERSION"
          git push

  release:
    needs: version

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: New release for ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  snapshot:
    needs: [ version, release ]

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update rc version
        run: |
          git config --global user.email "espaciocleos@gmail.com"
          git config --global user.name "Espacio Cleos"
          git fetch
          git checkout develop
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/version-update.sh"

          # run script
          "${GITHUB_WORKSPACE}/version-update.sh" true
          git commit -am "Update rc version"
          git push
