name: Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  version:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release version
        id: version
        run: |
          git config --global user.email "espaciocleos@gmail.com"
          git config --global user.name "Espacio Cleos"
          git fetch
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/version-update.sh"

          # run script
          VERSION=$("${GITHUB_WORKSPACE}/version-update.sh")
          git commit -am "Release version $VERSION"
          git push
