on:
  schedule:
    # Runs "at 05:00, only on Sunday"
    - cron: '0 5 * * 0'

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: nails-cleos
          number: 1
          token: ${{ secrets.TOKEN_READ }}
          iteration-field: Iteration
          iteration: last
          new-iteration: current
          statuses: Todo,In Progress,Blocked
